name: Build and run tests

on:
  pull_request:
    branches: ["*"]

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name of pull request
        run: |
            echo Branch name: ${{ github.event.pull_request.head.ref }}
        
      - name: Run tests
        run: |
            ./run_tests ${{ github.event.pull_request.head.ref }}